# Ref: https://rust-lang.github.io/rustfmt/?version=v1.5.2&search=

brace_style = "PreferSameLine"
fn_params_layout = "Compressed"
use_field_init_shorthand = true
max_width = 175
imports_granularity="Crate"
group_imports = "StdExternalCrate"
use_small_heuristics = "Max"
fn_call_width = 170
